name: Weekly S&P 500 Update

on:
  schedule:
    # At 14:00 UTC every Thursday
    - cron: '0 16 * * 4'

jobs:
  update-sp500:
    name: Run S&P 500 Scraper
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London  # Set runner logs to local time

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests yfinance numba

      - name: Run S&P 500 update script
        run: python sp500.py

      - name: Upload generated CSV
        uses: actions/upload-artifact@v3
        with:
          name: sp500-csv
          path: SP500.csv
