name: Weekly S&P 500 Update

on:
  schedule:
    # At 19:45 UTC every Saturday
    - cron: '45 20 * * 6'

jobs:
  update-sp500:
    name: Run S&P 500 Scraper
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests yfinance numba lxml

      - name: Run S&P 500 update script
        run: python SP500.py

      - name: Commit updated SP500.csv to new branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update SP500.csv [skip ci]"
          add: SP500.csv
          new_branch: update-sp500-${{ github.run_number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-sp500-${{ github.run_number }}
          title: "Weekly S&P 500 Update"
          body: "Automated update of SP500.csv"
          base: main
